"""empty message

Revision ID: 95e3039e1515
Revises: cec1392f823d
Create Date: 2026-02-04 12:01:38.762857

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "95e3039e1515"
down_revision: Union[str, Sequence[str], None] = "cec1392f823d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("repo_url", sa.Text(), nullable=True))
    op.add_column(
        "projects", sa.Column("git_branch", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "projects", sa.Column("git_token_env_key", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "git_token_env_key")
    op.drop_column("projects", "git_branch")
    op.drop_column("projects", "repo_url")
    # ### end Alembic commands ###
