"""empty message

Revision ID: e1c0ccb93e57
Revises: 0f0033af79a0
Create Date: 2026-01-28 22:49:37.164526

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e1c0ccb93e57"
down_revision: Union[str, Sequence[str], None] = "0f0033af79a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    fk_agent_runs_scheduled_task_id = "agent_runs_scheduled_task_id_fkey"
    op.create_table(
        "agent_scheduled_tasks",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "reuse_session",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("cron", sa.String(length=100), nullable=False),
        sa.Column(
            "timezone",
            sa.String(length=64),
            server_default=sa.text("'UTC'"),
            nullable=False,
        ),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("config_snapshot", sa.JSON(), nullable=True),
        sa.Column("input_files", sa.JSON(), nullable=True),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_run_id", sa.Uuid(), nullable=True),
        sa.Column("last_run_status", sa.String(length=50), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["agent_sessions.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_scheduled_tasks_enabled"),
        "agent_scheduled_tasks",
        ["enabled"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_scheduled_tasks_is_deleted"),
        "agent_scheduled_tasks",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_scheduled_tasks_last_run_id"),
        "agent_scheduled_tasks",
        ["last_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_scheduled_tasks_next_run_at"),
        "agent_scheduled_tasks",
        ["next_run_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_scheduled_tasks_session_id"),
        "agent_scheduled_tasks",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_scheduled_tasks_user_id"),
        "agent_scheduled_tasks",
        ["user_id"],
        unique=False,
    )
    op.add_column(
        "agent_runs", sa.Column("scheduled_task_id", sa.Uuid(), nullable=True)
    )
    op.create_index(
        op.f("ix_agent_runs_scheduled_task_id"),
        "agent_runs",
        ["scheduled_task_id"],
        unique=False,
    )
    op.create_foreign_key(
        fk_agent_runs_scheduled_task_id,
        "agent_runs",
        "agent_scheduled_tasks",
        ["scheduled_task_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "agent_sessions",
        sa.Column(
            "kind",
            sa.String(length=50),
            server_default=sa.text("'chat'"),
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_agent_sessions_kind"), "agent_sessions", ["kind"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    fk_agent_runs_scheduled_task_id = "agent_runs_scheduled_task_id_fkey"
    op.drop_index(op.f("ix_agent_sessions_kind"), table_name="agent_sessions")
    op.drop_column("agent_sessions", "kind")
    op.drop_constraint(
        fk_agent_runs_scheduled_task_id, "agent_runs", type_="foreignkey"
    )
    op.drop_index(op.f("ix_agent_runs_scheduled_task_id"), table_name="agent_runs")
    op.drop_column("agent_runs", "scheduled_task_id")
    op.drop_index(
        op.f("ix_agent_scheduled_tasks_user_id"), table_name="agent_scheduled_tasks"
    )
    op.drop_index(
        op.f("ix_agent_scheduled_tasks_session_id"), table_name="agent_scheduled_tasks"
    )
    op.drop_index(
        op.f("ix_agent_scheduled_tasks_next_run_at"), table_name="agent_scheduled_tasks"
    )
    op.drop_index(
        op.f("ix_agent_scheduled_tasks_last_run_id"), table_name="agent_scheduled_tasks"
    )
    op.drop_index(
        op.f("ix_agent_scheduled_tasks_is_deleted"), table_name="agent_scheduled_tasks"
    )
    op.drop_index(
        op.f("ix_agent_scheduled_tasks_enabled"), table_name="agent_scheduled_tasks"
    )
    op.drop_table("agent_scheduled_tasks")
    # ### end Alembic commands ###
